name: CI

on:
  pull_request:
    branches:
    - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Setup Bazel
      uses: bazelbuild/setup-bazelisk@v2
    -
      name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/bazel
        key: bazel
    -
      name: Test
      run: |
        bazel test //...

