name: Release and Push

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Setup Bazel
      uses: bazelbuild/setup-bazelisk@v2
    -
      name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/bazel
        key: bazel
    -
      name: Build
      if: github.event_name != 'pull_request'
      run: |
        bazel build //...
    -
      name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      if: github.event_name != 'pull_request'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install --no-package-lock @semantic-release/exec
        npx semantic-release
