name: Publish Docker image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/bazel
          key: bazel
      -
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17' # The Go version to download (if necessary) and use.

      -
        name: Install Bazelisk
        run: |
          go install github.com/bazelbuild/bazelisk@latest
      -
        name: Test
        run: |
          make test

  release:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/bazel
          key: bazel
      -
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17' # The Go version to download (if necessary) and use.
      -
        name: Install Bazelisk
        run: |
          go install github.com/bazelbuild/bazelisk@latest
      -
        uses: actions/setup-node@v1
        with:
          node-version: 14
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install --no-package-lock @semantic-release/exec
          npx semantic-release